---

- name: Set password minimum length
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: '^minlen'
    line: "minlen = {{ password_minlen }}"

- name: Set password maximum length (example using PAM)
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '.*pam_pwquality.so.*'
    line: "password requisite pam_pwquality.so retry=3 minlen={{ password_minlen }} maxlen={{ password_maxlen }}"
